// design-sync prep for @jrk/design. Run this before package-build.mjs /
// resync.mjs (it is `cfg.buildCmd`, so a re-sync picks it up automatically).
//
// The library ships TS source and an @import-manifest stylesheet rather than a
// compiled dist, so the converter needs three inputs synthesized first:
//
//   1. dist/            — the token layer (the repo's own `npm run build`).
//   2. dist/types/ + a root index.d.ts shim — the .d.ts tree the converter reads
//      as the component list and the API contract. `projectFor` resolves the
//      entry as <pkgRoot>/index.d.ts via pkgJson.types, which this package
//      deliberately does not declare (it publishes react/src/*.ts), so the shim
//      bridges the two without touching package.json.
//   3. .design-sync/.cache/jrk-flat.css — css/index.css is a pure @import
//      manifest; copied verbatim it lands as an unresolvable stub and every
//      component renders unstyled. esbuild inlines the imports into one real
//      stylesheet, which is what cfg.cssEntry points at.
//
// All three outputs are gitignored and regenerated; nothing here mutates the
// library's committed files.

import { spawnSync } from 'node:child_process';
import { createRequire } from 'node:module';
import { copyFileSync, mkdirSync, readdirSync, writeFileSync } from 'node:fs';
import { basename, dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const CSS_OUT = join(ROOT, '.design-sync', '.cache', 'jrk-flat.css');

const step = (msg) => console.error(`» ${msg}`);
const die = (msg) => { console.error(`✗ ${msg}`); process.exit(1); };

function run(args, label) {
  const r = spawnSync(process.execPath, args, { cwd: ROOT, stdio: 'inherit' });
  if (r.status !== 0) die(`${label} failed (exit ${r.status})`);
}

// 1. Token layer — the repo's own build (scripts/build-tokens.mjs, i.e.
//    `npm run build`). Invoked directly so no shell/npm wrapper is needed.
step('building token layer (dist/)');
run([join(ROOT, 'scripts', 'build-tokens.mjs')], 'token build');

// 2. Declaration tree + root entry shim.
step('emitting declarations (dist/types/)');
const repoRequire = createRequire(pathToFileURL(join(ROOT, 'package.json')));
let tscBin;
try {
  tscBin = repoRequire.resolve('typescript/bin/tsc');
} catch {
  die('typescript not found in node_modules — run `npm ci` first');
}
run([tscBin, '-p', join(ROOT, '.design-sync', 'tsconfig.dts.json')], 'tsc declaration emit');

writeFileSync(
  join(ROOT, 'index.d.ts'),
  '// Generated by .design-sync/prepare.mjs (gitignored). Entry shim so the\n' +
    "// converter's .d.ts resolver finds the tree emitted into dist/types/.\n" +
    "export * from './dist/types/index';\n",
);

// 3. Flatten the stylesheet. esbuild lives in the staged converter deps
//    (.ds-sync/node_modules), installed alongside ts-morph — see NOTES.md.
step('flattening stylesheet (.design-sync/.cache/jrk-flat.css)');
const dsRequire = createRequire(pathToFileURL(join(ROOT, '.ds-sync', 'package.json')));
let esbuild;
try {
  esbuild = await import(pathToFileURL(dsRequire.resolve('esbuild')).href);
} catch {
  die('esbuild not found — run `npm i esbuild ts-morph @types/react` in .ds-sync/');
}

mkdirSync(dirname(CSS_OUT), { recursive: true });
const res = await esbuild.build({
  entryPoints: [join(ROOT, 'css', 'index.css')],
  bundle: true,
  outfile: CSS_OUT,
  logLevel: 'warning',
  // Every url() in this library is an inline data: URI, so no asset loaders
  // are needed. A real file reference would fail loudly here rather than
  // silently shipping a broken path.
  external: [],
});
if (res.errors?.length) die(`css flatten failed: ${res.errors[0].text}`);

// 4. Stage the design-guideline docs under a plain `guides/` dir. They live in
//    .claude/skills/jrk-design/ in this repo, but the converter mirrors the
//    package-relative path into guidelines/, and the upload API refuses any
//    path under `.claude/` (reserved). Copying to guides/ keeps the same
//    content reachable at a legal destination.
step('staging design guidelines (guides/)');
const SKILL_DIR = join(ROOT, '.claude', 'skills', 'jrk-design');
const GUIDES = join(ROOT, 'guides');
mkdirSync(GUIDES, { recursive: true });
const guideSrcs = [
  join(SKILL_DIR, 'SKILL.md'),
  ...readdirSync(join(SKILL_DIR, 'references'))
    .filter((f) => f.endsWith('.md'))
    .map((f) => join(SKILL_DIR, 'references', f)),
];
for (const src of guideSrcs) {
  // SKILL.md is the library's own overview; keep a self-describing name.
  const dest = join(GUIDES, basename(src) === 'SKILL.md' ? 'jrk-design-overview.md' : basename(src));
  copyFileSync(src, dest);
}
console.error(`  ${guideSrcs.length} guideline file(s) → guides/`);

console.error('✓ prepare complete — dist/, dist/types/ + index.d.ts, jrk-flat.css, guides/');
