#!/usr/bin/env node
/**
 * Generates guides/ from the jrk-design skill.
 *
 *   .claude/skills/jrk-design/SKILL.md        -> guides/jrk-design-overview.md
 *   .claude/skills/jrk-design/references/*.md -> guides/*.md
 *
 * Why this exists: `.design-sync/config.json` points `guidelinesGlob` at
 * `guides/*.md`, and those files were previously HAND-COPIED from the skill.
 * They drifted — two of five still described the pre-Apple palette long after
 * the tokens changed, and because guides/ is gitignored the drift was invisible
 * in review while still being what the design agent read.
 *
 * One source (the skill), one generated output (guides/). Same pattern as
 * tokens.json -> dist/.
 */
import { readFileSync, writeFileSync, mkdirSync, readdirSync, rmSync, existsSync } from 'node:fs';
import { dirname, join, basename } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const skillDir = join(root, '.claude/skills/jrk-design');
const outDir = join(root, 'guides');

const BANNER = (src) =>
  `<!-- GENERATED by scripts/build-guides.mjs from ${src} — do not edit.\n` +
  `     Edit the skill; this file is regenerated by \`npm run build\`. -->\n\n`;

/** The skill's frontmatter is Claude Code plumbing (paths, when_to_use,
 *  invocation triggers). The design agent needs the prose, not the wiring. */
function stripFrontmatter(md) {
  return md.startsWith('---') ? md.slice(md.indexOf('\n---', 3) + 4).replace(/^\s*\n/, '') : md;
}

if (!existsSync(skillDir)) {
  console.error(`no skill at ${skillDir} — nothing to generate`);
  process.exit(1);
}

// Rebuild from scratch, so a reference deleted from the skill also disappears
// from guides/ rather than lingering as a stale orphan.
rmSync(outDir, { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });

const written = [];

const overview = stripFrontmatter(readFileSync(join(skillDir, 'SKILL.md'), 'utf8'));
writeFileSync(
  join(outDir, 'jrk-design-overview.md'),
  BANNER('.claude/skills/jrk-design/SKILL.md') + overview,
);
written.push('jrk-design-overview.md');

const refDir = join(skillDir, 'references');
for (const f of readdirSync(refDir).filter((n) => n.endsWith('.md')).sort()) {
  writeFileSync(
    join(outDir, f),
    BANNER(`.claude/skills/jrk-design/references/${f}`) + readFileSync(join(refDir, f), 'utf8'),
  );
  written.push(f);
}

console.log(`built guides/  ${written.length} files from the jrk-design skill`);
written.forEach((f) => console.log(`  ${f}`));
